"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footbar from "@/components/Footbar";
import { CartProvider } from "@/components/CartContext";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "test adityamms",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <CartProvider>
            <Navbar />
            {children}
            <Footbar />
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
